/**
 * Server Configuration
 * Supports both development (localhost) and production (GCP) environments
 */

module.exports = {
    // Server port (use environment variable in production)
    PORT: process.env.PORT || 3000,

    // Admin secret for authentication (loaded from .env file, generated by setup.js)
    ADMIN_SECRET: process.env.ADMIN_SECRET,

    // CORS settings
    CORS_ORIGIN: process.env.CORS_ORIGIN || 'http://localhost:8080',

    // Game settings
    DEFAULT_GAME_DURATION: 60,  // seconds
    MAX_PLAYERS_PER_TEAM: 100,
    SCORE_UPDATE_THROTTLE: 100,  // ms between broadcasts

    // Security
    BCRYPT_ROUNDS: 10,
    MAX_NAME_LENGTH: 50,
    MAX_PASSWORD_LENGTH: 100,

    // Rate limiting
    MAX_SCORE_UPDATES_PER_SECOND: 10,
};
